version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    groups:
      site-dev-dependencies:
        dependency-type: development
        patterns:
          - "*"
      site-runtime-dependencies:
        dependency-type: production
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
