name: 🚀 Feature Request
description: Suggest an idea or enhancement for MuseumSpark
title: "[Feature]: "
labels: ["enhancement", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving MuseumSpark!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when I can't filter by collection size...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions you've considered.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this feature for your workflow?
      options:
        - Critical (Blocking)
        - High (Important)
        - Medium (Nice to have)
        - Low (Cosmetic/Minor)
    validations:
      required: true
